/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package thithpqg;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class DangnhapJpanl extends javax.swing.JPanel {

    /**
     * Creates new form DangnhapJpanl
     */
    public DangnhapJpanl() {
        initComponents();
    }
public void setBg(Color a){
this.setBackground(a);
this.jPanel1.setBackground(a);
this.jPanel2.setBackground(a);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMK = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnDN = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thí Sinh Đăng Nhập");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 10, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/us.png"))); // NOI18N
        jLabel2.setText("Số CMND");
        jPanel1.add(jLabel2);

        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtID.setPreferredSize(new java.awt.Dimension(10, 30));
        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDFocusLost(evt);
            }
        });
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });
        jPanel1.add(txtID);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ps.png"))); // NOI18N
        jLabel3.setText("Mật Khẩu");
        jPanel1.add(jLabel3);

        txtMK.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtMK.setMinimumSize(new java.awt.Dimension(6, 10));
        txtMK.setPreferredSize(new java.awt.Dimension(10, 30));
        jPanel1.add(txtMK);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        btnDN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnDN.setText("Đăng Nhập");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });
        jPanel2.add(btnDN);

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setMaximumSize(new java.awt.Dimension(87, 23));
        btnHuy.setMinimumSize(new java.awt.Dimension(87, 23));
        btnHuy.setPreferredSize(new java.awt.Dimension(87, 25));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel2.add(btnHuy);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    //******************************************************************
    public void initText(){txtID.setText("");
       txtMK.setText("");}
    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
       if(txtID.getText().length()>0&& txtMK.getText().length()>0){
        try {
          ThiTHPTFrame.ts= Students.Login(txtID.getText(),txtMK.getText());
           if(ThiTHPTFrame.ts!=null){
           ThiTHPTFrame.setEnable(true);
           initText();
           ThiTHPTFrame.formDangkymonthi=new FormDangkymonthi();
           ThiTHPTFrame.formDoiMatKau=new FormDoiMatKau();
           ThiTHPTFrame.fromLichThi=new FromLichThi();
           ThiTHPTFrame.fromXemDiem=new FromXemDiem();
           ThiTHPTFrame.dangkicumthi=new Dangkicumthi();
           ThiTHPTFrame.formSuaHoSo=new FormSuaHoSo();
           JOptionPane.showMessageDialog(null, "Xin Chào "+ ThiTHPTFrame.ts.getHo() +ThiTHPTFrame.ts.getTen(),
                  "Thông báo", JOptionPane.DEFAULT_OPTION);
           }else{ JOptionPane.showMessageDialog(null, "Đăng nhập thất bại!",
                  "Thông báo", JOptionPane.INFORMATION_MESSAGE);}
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DangnhapJpanl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DangnhapJpanl.class.getName()).log(Level.SEVERE, null, ex);
        }
       }else{
           JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!",
                  "Thông báo", JOptionPane.INFORMATION_MESSAGE);}
       
    }//GEN-LAST:event_btnDNActionPerformed
    //******************************************************************
    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
       initText();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed

    }//GEN-LAST:event_txtIDActionPerformed
    //******************************************************************
    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        String kt= evt.getKeyChar()+"";
        try {
             int n=Integer.parseInt(kt+"");
      if(n<0 || n>9){evt.setKeyChar('\0');}
        } catch (NumberFormatException e) {
            evt.setKeyChar('\0');
             
        }
    }//GEN-LAST:event_txtIDKeyTyped
    //******************************************************************
    private void txtIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusLost
          if(txtID.getText().length()!=9 && txtID.getText().length()!=12){
        JOptionPane.showMessageDialog(null, "Nhập sai sô CMND",
                  "Thông báo", JOptionPane.INFORMATION_MESSAGE);
       initText();
        txtID.requestFocus();
       }
    }//GEN-LAST:event_txtIDFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDN;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMK;
    // End of variables declaration//GEN-END:variables
}
