/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package thithpqg;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Dangkicumthi extends javax.swing.JPanel {
    public Dangkicumthi() throws ClassNotFoundException {
        initComponents();
        initcombobox();
    }
public void initcombobox() throws ClassNotFoundException{
    DefaultComboBoxModel model=new DefaultComboBoxModel();
    for(int i=0;i<CumThi.caccumthi().size();i++){
     model.addElement(CumThi.caccumthi().get(i).toString());
    }
    cbxCum.setModel(model);
}
public void setBg(Color a){
this.setBackground(a);
this.jPanel1.setBackground(a);
this.jPanel2.setBackground(a);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtscmnd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxCum = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnDK = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG KÍ CỤM THI THPTQG");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nhập SCMND");
        jPanel1.add(jLabel2);
        jPanel1.add(txtscmnd);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Chọn Cụm thi");
        jPanel1.add(jLabel3);

        jPanel1.add(cbxCum);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        btnDK.setText("Đăng Ký");
        btnDK.setPreferredSize(new java.awt.Dimension(87, 23));
        btnDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKActionPerformed(evt);
            }
        });
        jPanel2.add(btnDK);

        btnHuy.setText("Hủy");
        btnHuy.setPreferredSize(new java.awt.Dimension(87, 23));
        jPanel2.add(btnHuy);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKActionPerformed
       Students d=new Students();
        try {
       int c=d.DangKyCumThi(cbxCum.getSelectedItem().toString(),txtscmnd.getText().toString());
       if(c!=0){
       JOptionPane.showMessageDialog(null, "Ma dang ki cua ban la:  "+c,"Thong bao", JOptionPane.DEFAULT_OPTION);
       }else{JOptionPane.showMessageDialog(null, "Dang ki khong thanh cong!","Thong bao", JOptionPane.DEFAULT_OPTION);}
       } catch (ClassNotFoundException ex) {
       Logger.getLogger(Dangkicumthi.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnDKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDK;
    private javax.swing.JButton btnHuy;
    private javax.swing.JComboBox cbxCum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtscmnd;
    // End of variables declaration//GEN-END:variables
}
