/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package thithpqg;

import java.awt.Color;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FormHoSoThiSinh extends javax.swing.JPanel {
    public FormHoSoThiSinh() throws ClassNotFoundException, SQLException {
        initComponents();
       initRadiobt();
         setcbDP();
    
    }
    
    public void setBg(Color a){
    this.setBackground(a);
    this.jPanel1.setBackground(a);
    this.jPanel2.setBackground(a);
    }
    //******************************************************************
public void setcbTHPT(String matinh) throws ClassNotFoundException{
   Vector c=THPT.getAll(matinh);
    DefaultComboBoxModel model=new DefaultComboBoxModel(c);
    cbTHPT.setModel(model);
}
    //******************************************************************
public  void setcbDP() throws ClassNotFoundException, SQLException{
 
     Vector  c=DiaPhuong.getAllDP();
        DefaultComboBoxModel model=new DefaultComboBoxModel(c);
    cbDiaphuong.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtscmnd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgaysinh = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pnGioiTinh = new javax.swing.JPanel();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cbDoituong = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cbKhuvuc = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbDiaphuong = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cbTHPT = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnDK = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG KÍ CỤM THI THPTQG");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 0, 5));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("          Nhập SCMND");
        jPanel1.add(jLabel2);

        txtscmnd.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N
        txtscmnd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtscmndFocusLost(evt);
            }
        });
        txtscmnd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtscmndKeyTyped(evt);
            }
        });
        jPanel1.add(txtscmnd);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("          Họ");
        jPanel1.add(jLabel4);

        txtHo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(txtHo);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("          Tên");
        jPanel1.add(jLabel5);

        txtTen.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(txtTen);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("          Ngày Sinh");
        jPanel1.add(jLabel6);

        txtNgaysinh.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(txtNgaysinh);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("          Tạo Mật khẩu ");
        jPanel1.add(jLabel11);

        txtMK.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(txtMK);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("          Giới tính");
        jPanel1.add(jLabel3);

        pnGioiTinh.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        rbNam.setSelected(true);
        rbNam.setText("Nam");
        pnGioiTinh.add(rbNam);

        rbNu.setText("Nữ");
        pnGioiTinh.add(rbNu);

        jPanel1.add(pnGioiTinh);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("          Đối tượng");
        jPanel1.add(jLabel7);

        cbDoituong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gia đình TB-LS", "Gia đình cách mạng", " " }));
        jPanel1.add(cbDoituong);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("          Khu vực");
        jPanel1.add(jLabel8);

        cbKhuvuc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "2NT", "3" }));
        jPanel1.add(cbKhuvuc);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("          Địa phương");
        jPanel1.add(jLabel9);

        cbDiaphuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiaphuongActionPerformed(evt);
            }
        });
        jPanel1.add(cbDiaphuong);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("          Trường THPT");
        jPanel1.add(jLabel10);

        jPanel1.add(cbTHPT);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        btnDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnDK.setText("Đăng Ký");
        btnDK.setPreferredSize(new java.awt.Dimension(150, 30));
        btnDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKActionPerformed(evt);
            }
        });
        jPanel2.add(btnDK);

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel2.add(btnHuy);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    //******************************************************************
    public boolean kiemtranull(){
    boolean flag=false;
    if(!"".equals(txtscmnd.getText()) && !"".equals(txtHo.getText())&&!"".equals(txtTen.getText())&&!"".equals(txtMK.getText())&!"".equals(txtNgaysinh.getText())){
    flag=true;
    }
return flag;
}
        //******************************************************************
    private void btnDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKActionPerformed
 //Students a=new Students("206047189","Dương Công ","Thành","B","2","1234","1","07/07/97","04-001");   
       if(kiemtranull()==true){
           String gt="";
            try {
        if(rbNam.isSelected()){gt="B";}else{gt="G";}
        String dt="";
        if(cbDoituong.getSelectedIndex()==1){dt="1";}else{dt="2";}
        Students c=new Students(txtscmnd.getText(),
                txtHo.getText(),
                txtTen.getText(),
                gt,
                 cbKhuvuc.getSelectedItem().toString(),
                 txtMK.getText(),
                dt,
                txtNgaysinh.getText(),  
                cbTHPT.getSelectedItem().toString().substring(0,6)
        );
       
           boolean rs= c.Connect_insertdatabase();
           if(rs==true){  JOptionPane.showMessageDialog(null,"Đăng kí thành công",
                  "Thông báo", JOptionPane.INFORMATION_MESSAGE);}
           else{ JOptionPane.showMessageDialog(null,"Đăng kí không thành công",
                  "Thông báo", JOptionPane.INFORMATION_MESSAGE);}
          
        }catch(java.lang.NullPointerException e){
         JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin",
                  "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Sự cố!Rất tiếc",
                  "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
       }else{
       JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin",
                  "Thông báo", JOptionPane.INFORMATION_MESSAGE);
       } 
     
    }//GEN-LAST:event_btnDKActionPerformed
    //******************************************************************
    private void txtscmndKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtscmndKeyTyped
        String kt= evt.getKeyChar()+"";
        try {
             int n=Integer.parseInt(kt+"");
      if(n<0 || n>9){evt.setKeyChar('\0');}
        } catch (NumberFormatException e) {
            evt.setKeyChar('\0');
             
        }
       
    }//GEN-LAST:event_txtscmndKeyTyped
    //******************************************************************
    private void txtscmndFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtscmndFocusLost
       if(txtscmnd.getText().length()!=9 && txtscmnd.getText().length()!=12){
        JOptionPane.showMessageDialog(null, "Nhập sai sô CMND",
                  "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        txtscmnd.setText("");
        txtscmnd.requestFocus();
       }
    }//GEN-LAST:event_txtscmndFocusLost
    //******************************************************************
    private void cbDiaphuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiaphuongActionPerformed
      String matinh=(String) cbDiaphuong.getSelectedItem().toString().substring(0,5);
        try {
            setcbTHPT(matinh);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormHoSoThiSinh.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_cbDiaphuongActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDK;
    private javax.swing.JButton btnHuy;
    private javax.swing.JComboBox cbDiaphuong;
    private javax.swing.JComboBox cbDoituong;
    private javax.swing.JComboBox cbKhuvuc;
    private javax.swing.JComboBox cbTHPT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnGioiTinh;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMK;
    private javax.swing.JTextField txtNgaysinh;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtscmnd;
    // End of variables declaration//GEN-END:variables

    private void initRadiobt() {
        ButtonGroup group=new ButtonGroup();
        group.add(rbNam);
        group.add(rbNu);
    }
}
