/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package thithpqg;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public  class FormDangkymonthi extends javax.swing.JPanel {
    /**
     * Creates new form FormDangkymonthi
     */

    public  FormDangkymonthi() throws ClassNotFoundException {
        initComponents();
         hienthiDK();
          hienthidaDK();
    }
    public void setBg(Color a){
    this.setBackground(a);
    this.jPanel3.setBackground(a);
    this.jPanel5.setBackground(a);
    this.jPanel6.setBackground(a);
    this.TableDK.setBackground(a);
    this.parentPanel.setBackground(a);
    this.tbSua.setBackground(a);
    }
  //----------------------------------------------------  
    ArrayList<JCheckBox> checkDK;
    ArrayList<JCheckBox> checkdaDK;

//----------------------------------------------------
public void initMang() throws ClassNotFoundException{checkDK=new ArrayList();}
public void initMangb() throws ClassNotFoundException{  checkdaDK=new ArrayList();}
//----------------------------------------------------
public void tieudeTable(JPanel a){
 JLabel m[]={new JLabel("Mã Môn"),
        new JLabel("Tên Môn"),
        new JLabel("Hệ Số"),
        new JLabel("Đăng Ký"),
        new JLabel("Ngày Thi"),
        new JLabel("Giờ Thi " )
        };      
        for(int i=0;i<m.length;i++){
        a.add(m[i]);
        }
}
//----------------------------------------------------
public void hienthiDK() throws ClassNotFoundException{
    
       initMang();
  TableDK.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
       tieudeTable(TableDK);
        for(int i=0;i<MonThi.returnMonthiS().size();i++){
        TableDK.add(new JLabel(MonThi.returnMonthiS().get(i).getMaMon()));
        TableDK.add(new JLabel(MonThi.returnMonthiS().get(i).getTenMon()));
        TableDK.add(new JLabel(MonThi.returnMonthiS().get(i).getHeSo()+""));
        checkDK.add(new JCheckBox("Chọn"));
        TableDK.add(checkDK.get(i));
        TableDK.add(new JLabel(MonThi.returnMonthiS().get(i).getNgaythi()+""));
        TableDK.add(new JLabel(MonThi.returnMonthiS().get(i).getGiothi()+""));
        }
        parentPanel.removeAll();
        parentPanel.add(TableDK);
}

//----------------------------------------------------------------------
public void hienthidaDK() throws ClassNotFoundException{
    tbSua.removeAll();
    initMangb();
 tbSua.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
 tieudeTable(tbSua);
        for(int i=0;i<ThiTHPTFrame.ts.returnMonthidaDK().size();i++){
  tbSua.add(new JLabel(ThiTHPTFrame.ts.returnMonthidaDK().get(i).getMaMon()));
        tbSua.add(new JLabel(ThiTHPTFrame.ts.returnMonthidaDK().get(i).getTenMon()));
        tbSua.add(new JLabel(""+ThiTHPTFrame.ts.returnMonthidaDK().get(i).getHeSo()));
         checkdaDK.add(new JCheckBox("Chọn"));
        tbSua.add(checkdaDK.get(i));
        tbSua.add(new JLabel(ThiTHPTFrame.ts.returnMonthidaDK().get(i).getNgaythi().toString()));
        tbSua.add(new JLabel(ThiTHPTFrame.ts.returnMonthidaDK().get(i).getGiothi().toString()));
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTieude = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        TableDK = new javax.swing.JPanel();
        tbSua = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMADK = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtDK_HuyDk = new javax.swing.JButton();
        xem_quayve = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        txtTieude.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTieude.setText("Đăng Ký Môn Thi");
        txtTieude.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        add(txtTieude, java.awt.BorderLayout.PAGE_START);

        parentPanel.setLayout(new java.awt.CardLayout());

        TableDK.setBackground(new java.awt.Color(204, 255, 0));
        TableDK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        TableDK.setLayout(new java.awt.GridLayout(0, 6, 50, 2));
        parentPanel.add(TableDK, "card2");

        tbSua.setBackground(new java.awt.Color(102, 255, 102));
        tbSua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        tbSua.setLayout(new java.awt.GridLayout(0, 6, 50, 2));
        parentPanel.add(tbSua, "card3");

        add(parentPanel, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Nhập mã DK");
        jPanel5.add(jLabel2);

        txtMADK.setPreferredSize(new java.awt.Dimension(70, 20));
        txtMADK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMADKKeyTyped(evt);
            }
        });
        jPanel5.add(txtMADK);

        jPanel3.add(jPanel5);

        txtDK_HuyDk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        txtDK_HuyDk.setText("Đăng Ký");
        txtDK_HuyDk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDK_HuyDkActionPerformed(evt);
            }
        });
        jPanel6.add(txtDK_HuyDk);

        xem_quayve.setText("Đã ĐK");
        xem_quayve.setPreferredSize(new java.awt.Dimension(93, 23));
        xem_quayve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xem_quayveActionPerformed(evt);
            }
        });
        jPanel6.add(xem_quayve);

        jPanel3.add(jPanel6);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void xem_quayveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xem_quayveActionPerformed
       if(xem_quayve.getText()=="Đã ĐK"){
           txtDK_HuyDk.setText("Hủy Đăng Ký");
          txtTieude.setText("Các Môn Đã Đăng Ký");
        parentPanel.removeAll();
        parentPanel.add(tbSua);
        parentPanel.repaint();
        parentPanel.revalidate();
        xem_quayve.setText("Back");
       
       }
       else{
            txtDK_HuyDk.setText("Đăng Ký");
            txtTieude.setText("Đăng Ký Môn Thi");
        parentPanel.removeAll();
        parentPanel.add(TableDK);
         parentPanel.repaint();
         parentPanel.revalidate();
          xem_quayve.setText("Đã ĐK");
       }
    }//GEN-LAST:event_xem_quayveActionPerformed
//----------------------------------------------------------------------
    private void txtDK_HuyDkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDK_HuyDkActionPerformed
        if(txtDK_HuyDk.getText()=="Đăng Ký"){ThucHienDK();}
         if(txtDK_HuyDk.getText()=="Hủy Đăng Ký"){ ThucHienXoaDK();}
    }//GEN-LAST:event_txtDK_HuyDkActionPerformed
//----------------------------------------------------------------------
    private void txtMADKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMADKKeyTyped
        String kt= evt.getKeyChar()+"";
        try {
             int n=Integer.parseInt(kt+"");
      if(n<0 || n>9){evt.setKeyChar('\0');}
        } catch (NumberFormatException e) {
            evt.setKeyChar('\0');
             
        }
    }//GEN-LAST:event_txtMADKKeyTyped
//----------------------------------------------------------------------
    public void ThucHienXoaDK(){
     if(txtMADK.getText().length()>0){
  ArrayList<MonThi> mon=new ArrayList();
        try {
            for(int i=0;i<ThiTHPTFrame.ts.returnMonthidaDK().size();i++){
                if(checkdaDK.get(i).isSelected()){
                    mon.add(new MonThi(ThiTHPTFrame.ts.returnMonthidaDK().get(i).getMaMon().toString()));
                }
            }
             if(mon.size()>0){
                        boolean a=Students.XoaMonThi(Integer.parseInt(txtMADK.getText()), mon);
                        if(a==true){JOptionPane.showMessageDialog(null, "Bạn đã xóa thành công",
                                "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        hienthidaDK();
                            parentPanel.removeAll();
              parentPanel.add(tbSua);
              parentPanel.repaint();
              parentPanel.revalidate();
              ThiTHPTFrame.fromLichThi=new FromLichThi();
              ThiTHPTFrame.fromXemDiem=new FromXemDiem();
                        }else{JOptionPane.showMessageDialog(null, "Lỗi khi xóa!Không đc thực hiện,có thể sai mã đăng ký",
                                "Thông báo", JOptionPane.INFORMATION_MESSAGE);}
                        
                    }else{JOptionPane.showMessageDialog(null, "Chọn Môn",
                            "Thông báo", JOptionPane.INFORMATION_MESSAGE);}
              initCheckbox();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormDangkymonthi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormDangkymonthi.class.getName()).log(Level.SEVERE, null, ex);
        }
            
     }else{JOptionPane.showMessageDialog(null, "Nhập Mã Đăng Ký",
                    "Thông báo", JOptionPane.INFORMATION_MESSAGE);}
}
//----------------------------------------------------------------------
  public void ThucHienDK(){
      if(txtMADK.getText().length()>0){
                ArrayList<MonThi> mon=new ArrayList();
                try {
                    for(int i=0;i<MonThi.returnMonthiS().size();i++){
                        if(checkDK.get(i).isSelected()){
                            mon.add(new MonThi(MonThi.returnMonthiS().get(i).getMaMon().toString()));
                        }
                    }
                    if(mon.size()>0){
                        boolean a=Students.DangKymonthi(Integer.parseInt(txtMADK.getText()), mon);
                        if(a==true){JOptionPane.showMessageDialog(null, "Bạn đã đăng kí thành công",
                                "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        hienthidaDK();
                        ThiTHPTFrame.fromLichThi=new FromLichThi();
                        ThiTHPTFrame.fromXemDiem=new FromXemDiem();
                        }else{JOptionPane.showMessageDialog(null, "Bạn đã đăng kí không thành công,có thể trùng môn,hoặc sai mã đăng ký",
                                "Thông báo", JOptionPane.INFORMATION_MESSAGE);}
                        
                    }else{JOptionPane.showMessageDialog(null, "Chọn Môn",
                            "Thông báo", JOptionPane.INFORMATION_MESSAGE);}
                    initCheckbox();
                }
                catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Sự cố!",
                            "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(FormDangkymonthi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{JOptionPane.showMessageDialog(null, "Nhập Mã Đăng Ký",
                    "Thông báo", JOptionPane.INFORMATION_MESSAGE);}
        }
      //******************************************************************
public void initCheckbox(){
        try {
            for(int i=0;i<MonThi.returnMonthiS().size();i++){
                checkDK.get(i).setSelected(false);
            }       } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormDangkymonthi.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            for(int i=0;i<ThiTHPTFrame.ts.returnMonthidaDK().size();i++){
                checkdaDK.get(i).setSelected(false);
            }       } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormDangkymonthi.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TableDK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JPanel tbSua;
    private javax.swing.JButton txtDK_HuyDk;
    private javax.swing.JTextField txtMADK;
    private javax.swing.JLabel txtTieude;
    private javax.swing.JButton xem_quayve;
    // End of variables declaration//GEN-END:variables
}
