

package thithpqg;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;


public class ThiTHPTFrame extends javax.swing.JFrame {
   static FormDangkymonthi formDangkymonthi;
   static FormDoiMatKau formDoiMatKau;
   static  FromLichThi fromLichThi;
   static  FromXemDiem fromXemDiem;
   static  Dangkicumthi dangkicumthi;
   static FormSuaHoSo formSuaHoSo;
   
   DangnhapJpanl dangnhapJpanl=new DangnhapJpanl();
    FormHoSoThiSinh formHoSoThiSinh=new FormHoSoThiSinh();
    FormTroGiup help=new FormTroGiup();

   
  public static Students ts=null;
    public ThiTHPTFrame() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setTitle("THITHPTQG");
        DongHo c=new DongHo();
         c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Thread t=new Thread(c);
        this.topPane.add(c,java.awt.BorderLayout.SOUTH);t.start();
        
    }
 //******************************************************************
public static void setEnable(boolean stt){
     mnDKCum.setEnabled(stt);
     mnDKMonThi.setEnabled(stt);
     mnXemLichCN.setEnabled(stt);
     thoat.setEnabled(stt);
     mnDMK.setEnabled(stt);
     mnXemdiem.setEnabled(stt);
     mnXemMaDK.setEnabled(stt);
     mnMau.setEnabled(stt);
     mnUpdateHS.setEnabled(stt);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Xulydn = new javax.swing.JSplitPane();
        topPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnThoat = new javax.swing.JMenu();
        dangnhap = new javax.swing.JMenuItem();
        mnDMK = new javax.swing.JMenuItem();
        thoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnXemMaDK = new javax.swing.JMenuItem();
        mnDKMonThi = new javax.swing.JMenuItem();
        mnDKCum = new javax.swing.JMenuItem();
        mnXemLichCN = new javax.swing.JMenuItem();
        mnXemdiem = new javax.swing.JMenuItem();
        mnUpdateHS = new javax.swing.JMenuItem();
        mnDKHS = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnMau = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Xulydn.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topPane.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Thi THPTQG");
        topPane.add(jLabel1, java.awt.BorderLayout.CENTER);

        Xulydn.setLeftComponent(topPane);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thí Sinh Cần Phải Đăng Nhập Để Xem Thông Tin");
        Xulydn.setBottomComponent(jLabel3);

        mnThoat.setText("Hệ Thống");

        dangnhap.setText("Đăng nhập");
        dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangnhapActionPerformed(evt);
            }
        });
        mnThoat.add(dangnhap);

        mnDMK.setText("Đổi Mật Khẩu");
        mnDMK.setEnabled(false);
        mnDMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDMKActionPerformed(evt);
            }
        });
        mnThoat.add(mnDMK);

        thoat.setText("Thoát");
        thoat.setEnabled(false);
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });
        mnThoat.add(thoat);

        jMenuBar1.add(mnThoat);

        jMenu2.setText("Thí sinh");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        mnXemMaDK.setText("Xem mã đăng ký");
        mnXemMaDK.setEnabled(false);
        mnXemMaDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnXemMaDKActionPerformed(evt);
            }
        });
        jMenu2.add(mnXemMaDK);

        mnDKMonThi.setText("Đăng kí môn thi");
        mnDKMonThi.setEnabled(false);
        mnDKMonThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDKMonThiActionPerformed(evt);
            }
        });
        jMenu2.add(mnDKMonThi);

        mnDKCum.setText("Đăng kí cụm thi");
        mnDKCum.setEnabled(false);
        mnDKCum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDKCumActionPerformed(evt);
            }
        });
        jMenu2.add(mnDKCum);

        mnXemLichCN.setText("Xem lịch thi");
        mnXemLichCN.setEnabled(false);
        mnXemLichCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnXemLichCNActionPerformed(evt);
            }
        });
        jMenu2.add(mnXemLichCN);

        mnXemdiem.setText("Xem điểm thi");
        mnXemdiem.setEnabled(false);
        mnXemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnXemdiemActionPerformed(evt);
            }
        });
        jMenu2.add(mnXemdiem);

        mnUpdateHS.setText("Cập nhật hồ sơ");
        mnUpdateHS.setEnabled(false);
        mnUpdateHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUpdateHSActionPerformed(evt);
            }
        });
        jMenu2.add(mnUpdateHS);

        mnDKHS.setText("Đăng kí hồ sơ");
        mnDKHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDKHSActionPerformed(evt);
            }
        });
        jMenu2.add(mnDKHS);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Admin");

        mnMau.setText("Chọn màu");
        mnMau.setEnabled(false);
        mnMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMauActionPerformed(evt);
            }
        });
        jMenu3.add(mnMau);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Trợ Giúp");

        jMenuItem1.setText("Hướng dẫn");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Xulydn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Xulydn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangnhapActionPerformed
        Xulydn.setBottomComponent(dangnhapJpanl);pack();
    }//GEN-LAST:event_dangnhapActionPerformed
 //******************************************************************
    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatActionPerformed
     JOptionPane.showMessageDialog(null, "Tạm biệt",
                  "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        ThiTHPTFrame.ts=null;
        setEnable(false);
        Xulydn.setBottomComponent(dangnhapJpanl);
         pack();
    }//GEN-LAST:event_thoatActionPerformed
 //******************************************************************
    private void mnDKCumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDKCumActionPerformed
 Xulydn.setBottomComponent(dangkicumthi); pack();
    }//GEN-LAST:event_mnDKCumActionPerformed
//******************************************************************
    private void mnDKMonThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDKMonThiActionPerformed
  Xulydn.setBottomComponent(formDangkymonthi); pack();
    }//GEN-LAST:event_mnDKMonThiActionPerformed
//******************************************************************
    private void mnDKHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDKHSActionPerformed
   Xulydn.setBottomComponent(formHoSoThiSinh); pack();  
    }//GEN-LAST:event_mnDKHSActionPerformed
//******************************************************************
    private void mnXemLichCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnXemLichCNActionPerformed
           Xulydn.setBottomComponent(fromLichThi); pack(); 
    }//GEN-LAST:event_mnXemLichCNActionPerformed
//******************************************************************
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
    
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void mnDMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDMKActionPerformed
       Xulydn.setBottomComponent(formDoiMatKau); pack();
    }//GEN-LAST:event_mnDMKActionPerformed
//******************************************************************
    private void mnXemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnXemdiemActionPerformed
      Xulydn.setBottomComponent(fromXemDiem); pack();
    }//GEN-LAST:event_mnXemdiemActionPerformed
//******************************************************************
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
Xulydn.setBottomComponent(help); pack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
//******************************************************************
    private void mnXemMaDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnXemMaDKActionPerformed
      try {
          int madk= ts.xemmadk();
          if(madk!=0){JOptionPane.showMessageDialog(null,"Mã đăng ký của bạn là: "+madk,
                  "Thông báo", JOptionPane.DEFAULT_OPTION);}else{
          JOptionPane.showMessageDialog(null,"Chưa có mã đăng ký!Vui lòng đăng ký cụm thi.",
                  "Thông báo", JOptionPane.DEFAULT_OPTION);
          }
          
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(ThiTHPTFrame.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(ThiTHPTFrame.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }//GEN-LAST:event_mnXemMaDKActionPerformed

    private void mnMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMauActionPerformed
        Color a=JColorChooser.showDialog(this,"Chọn màu nền",getBackground());
        this.Xulydn.setBackground(a);
        this.topPane.setBackground(a);
        this.dangnhapJpanl.setBg(a);
        this.formHoSoThiSinh.setBg(a);
        this.formHoSoThiSinh.setBg(a);
        formDangkymonthi.setBg(a);
        formDoiMatKau.setBg(a);
        fromLichThi.setBg(a);
        fromXemDiem.setBg(a);
        dangkicumthi.setBg(a);
        help.setBg(a);
        formSuaHoSo.setBg(a);
    }//GEN-LAST:event_mnMauActionPerformed

    private void mnUpdateHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUpdateHSActionPerformed
        Xulydn.setBottomComponent(formSuaHoSo); pack(); 
    }//GEN-LAST:event_mnUpdateHSActionPerformed
//******************************************************************
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ThiTHPTFrame().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ThiTHPTFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ThiTHPTFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane Xulydn;
    private javax.swing.JMenuItem dangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private static javax.swing.JMenuItem mnDKCum;
    private javax.swing.JMenuItem mnDKHS;
    private static javax.swing.JMenuItem mnDKMonThi;
    private static javax.swing.JMenuItem mnDMK;
    private static javax.swing.JMenuItem mnMau;
    private static javax.swing.JMenu mnThoat;
    private static javax.swing.JMenuItem mnUpdateHS;
    private static javax.swing.JMenuItem mnXemLichCN;
    private static javax.swing.JMenuItem mnXemMaDK;
    private static javax.swing.JMenuItem mnXemdiem;
    private static javax.swing.JMenuItem thoat;
    private javax.swing.JPanel topPane;
    // End of variables declaration//GEN-END:variables
}
